// 精英垂直弹跳学院 (EVA) 172个训练动作视频与教练中文讲解映射库
const EVA_EX_LINKS = {
  "Ab Wheel": "https://www.youtube.com/watch?v=j41bASIRzvo",
  "Alternating Lunge Jumps": "https://www.youtube.com/watch?v=FgtEMhlm8lg",
  "Alternating Sprinter Step Ups": "https://www.youtube.com/watch?v=Z_IiUhVs4HI",
  "Approach Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Approach Single Leg Box Jump": "https://www.youtube.com/watch?v=jxfGunNZaFw",
  "Approach Single Leg Vertical Jumps": "https://www.youtube.com/watch?v=qmiaSj_eT48",
  "Approach Tuck Jump to Low Squat Landing": "https://www.youtube.com/watch?v=qZh5XTdhrK8",
  "Approach Tuck Jump to Split Lunge Landing": "https://www.youtube.com/watch?v=QJskYpKndgw",
  "BB Curls": "https://www.youtube.com/watch?v=4tT6n_VEORA",
  "BB Iso Squat": "https://www.youtube.com/watch?v=EwkBcH1ghZ8",
  "BB Iso Sumo Squat": "https://www.youtube.com/watch?v=EwkBcH1ghZ8",
  "BB Oscillatory Low Squat": "https://www.youtube.com/watch?v=zoUyB1k62FU",
  "BB Oscillatory Sumo Squat": "https://www.youtube.com/watch?v=zoUyB1k62FU",
  "BB RDL": "https://www.youtube.com/watch?v=CtjDKM5MkvE",
  "BB Rack Pulls": "https://www.youtube.com/watch?v=4qtp361EZJg",
  "BB Reverse Lunge": "https://www.youtube.com/watch?v=gJAflXsoa6A",
  "Back Squat": "https://www.youtube.com/watch?v=w-Fe1iz5dyo",
  "Band Assisted Alternating Lunge Jumps": "https://www.youtube.com/watch?v=FgtEMhlm8lg",
  "Band Assisted Jumps": "https://www.youtube.com/watch?v=YAOWJdT__O4",
  "Band Assisted Single Leg Jumps": "https://www.youtube.com/watch?v=MxUsfUZNqkM",
  "Band Assisted Single Leg Pogos": "https://www.youtube.com/watch?v=Z7u6afb7JRE",
  "Band Assisted Squat Jumps": "https://www.youtube.com/watch?v=6mshdP-Oi80",
  "Band Assisted Stationary Alternating Pogo Jumps": "https://www.youtube.com/watch?v=Knvvx4Jpzak",
  "Band Assisted Stationary Pogos": "https://www.youtube.com/watch?v=WiA9B1iC6t0",
  "Band Assisted Stationary Pulsing Pogos": "https://www.youtube.com/watch?v=KfxXiLyeHQc",
  "Band Box Squat": "https://www.youtube.com/watch?v=9LEnmKXl--U",
  "Band Facepull to External Rotation": "https://www.youtube.com/watch?v=Uk_UlIhc6a4",
  "Band Facepulls": "https://www.youtube.com/watch?v=naKAEmPUWdw",
  "Band Glute Bridge with Abduction": "https://www.youtube.com/watch?v=6Brg1MgQcVA",
  "Band Pin Press": "https://www.youtube.com/watch?v=QtEAgxEeAKw",
  "Band Snatch": "https://www.youtube.com/watch?v=qMMjQxUjLeQ",
  "Band TKE’s": "https://www.youtube.com/watch?v=bU-Yb4KdpNw",
  "Band Tricep Extensions": "https://www.youtube.com/watch?v=VHFufUUSHig",
  "Banded Kettlebell Swing": "https://www.youtube.com/watch?v=fsyg_pZfarA",
  "Bench Press": "https://www.youtube.com/watch?v=wvEfyPtT44U",
  "Box Jump": "https://www.youtube.com/watch?v=jxfGunNZaFw",
  "Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Bulgarian Split Squat": "https://overtimeathletes.com/movements/strength/lower/unilateral-strength/iso-extreme-bulgarian-split-squat/",
  "Bulgarian Split Squat (Heel Raised)": "https://www.youtube.com/watch?v=RrP9PHcjj0g",
  "Bulgarian Split Squat (heel elevated)": "https://www.youtube.com/watch?v=RrP9PHcjj0g",
  "Bulgarian Split Squat Jumps": "https://www.youtube.com/watch?v=6mshdP-Oi80",
  "Bulgarian Split Squat to Foam": "https://www.youtube.com/watch?v=RrP9PHcjj0g",
  "Cable Tricep Extension": "https://www.youtube.com/watch?v=UZpPZ1O8uYo",
  "Cable Woodchops": "https://www.youtube.com/watch?v=j1cf5K0v_0k",
  "DB Alternating Lunge Jumps": "https://www.youtube.com/watch?v=FgtEMhlm8lg",
  "DB Hammer Curls": "https://www.youtube.com/watch?v=s1ZHxg7wiFA",
  "DB Iso Bulgarian Split Squat": "https://www.youtube.com/watch?v=RrP9PHcjj0g",
  "DB Iso Split Squat": "https://www.youtube.com/watch?v=GEuBgO1xRzc",
  "DB Linear Pogos": "https://www.youtube.com/watch?v=tyasPPd-wzs",
  "DB Oscillatory Bulgarian Split Squat": "https://www.youtube.com/watch?v=mVU8jNNmIqs",
  "DB Oscillatory Split Squat": "https://www.youtube.com/watch?v=AS7HIJ_q17A",
  "DB RDL": "https://www.youtube.com/watch?v=xEvkelNr_-A",
  "DB Reverse Lunge": "https://www.youtube.com/watch?v=gJAflXsoa6A",
  "DB Reverse Lunge (heel elevated)": "https://www.youtube.com/watch?v=gJAflXsoa6A",
  "DB Squat Jumps": "https://www.youtube.com/watch?v=6mshdP-Oi80",
  "DB Stationary Alternating Pogo Jumps": "https://www.youtube.com/watch?v=mW4vt3jcuAw",
  "DB Stationary Pogos": "https://www.youtube.com/watch?v=WiA9B1iC6t0",
  "DB Z Press": "http://overtimeathletes.com/movements/strength/upper/push/vertical/military-floor-press/",
  "Decel Sprinter Step Ups": "https://www.youtube.com/watch?v=VWUv_YoxGEw",
  "Decel Step Ups": "https://www.youtube.com/watch?v=WjkXTrwjMnE",
  "Depth Drops": "https://www.youtube.com/watch?v=7HdHLuAzBes",
  "Dump the Buckets": "https://www.youtube.com/watch?v=SCQ9DQeoE_c",
  "EZ Bar Curls": "https://www.youtube.com/watch?v=4tT6n_VEORA",
  "EZ Bar Skull Crushers": "https://www.youtube.com/watch?v=ZC-yUUQDJnA",
  "Eccentric Band Back Squat": "https://www.youtube.com/watch?v=eUEAAEOotnQ",
  "Eccentric Band Bench Press": "https://www.youtube.com/watch?v=27yX3UVniWw",
  "Eccentric Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Eccentric Single Leg Box Jumps": "https://www.youtube.com/watch?v=jxfGunNZaFw",
  "Elevated DB Reverse Lunge": "https://www.youtube.com/watch?v=gJAflXsoa6A",
  "Explosive Band Push Ups": "https://www.youtube.com/watch?v=5UZ5KEjUPOU",
  "Floor Press": "https://www.youtube.com/watch?v=WQK3Byyt1zk",
  "Goblet Lateral Lunge": "https://www.youtube.com/watch?v=DW6vMEt8vCI",
  "Half Kneeling Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Half Kneeling Landmine Press": "https://www.youtube.com/watch?v=b-5t7HOABqc",
  "Half Kneeling Vertical Toss": "https://www.youtube.com/watch?v=XjlSjGfc9cg",
  "Hanging Leg Raise": "https://www.youtube.com/watch?v=4Ch5YMjbTKA",
  "Hyperextensions": "https://www.youtube.com/watch?v=D_fgMVuDkgw",
  "Incline Alternating Row": "https://www.youtube.com/watch?v=Wqtg3bztCpY",
  "Incline DB Hammer Curls": "https://www.youtube.com/watch?v=s1ZHxg7wiFA",
  "Incline Plate Press": "https://www.youtube.com/watch?v=ZcciCMEC3mI",
  "Incline Rear Delt Raise": "https://www.youtube.com/watch?v=06NT9wsO95A",
  "Incline Rear Delt Raise with External Rotation": "https://www.youtube.com/watch?v=06NT9wsO95A",
  "Incline Row": "https://www.youtube.com/watch?v=Wqtg3bztCpY",
  "Iso Band Back Squat": "https://www.youtube.com/watch?v=w-Fe1iz5dyo",
  "Iso Band Bench Press": "https://www.youtube.com/watch?v=wvEfyPtT44U",
  "Iso Step Downs": "https://overtimeathletes.com/movements/stretches-activation-2/correctives/lower/iso-step-downs/",
  "Iso-Extreme Bulgarian Split Squat": "https://overtimeathletes.com/movements/strength/lower/unilateral-strength/iso-extreme-bulgarian-split-squat/",
  "Iso-Extreme Nordic Hamstrings": "https://www.youtube.com/watch?v=T_oN089mQbc",
  "Iso-Extreme SL Hip Thrust": "https://www.youtube.com/watch?v=kXUMRXNgs7o",
  "Iso-Extreme Split Squat": "https://www.youtube.com/watch?v=NIVtkEKNhaE",
  "Iso-Extreme Squat": "https://www.youtube.com/watch?v=T67pP7Jm6mw",
  "Iso-Extreme Sumo Squat": "https://www.youtube.com/watch?v=B84ZeeYb4yM",
  "Kettlebell Swing": "https://www.youtube.com/watch?v=fsyg_pZfarA",
  "Landmine Press": "https://www.youtube.com/watch?v=b-5t7HOABqc",
  "Larsen Bench Press": "https://www.youtube.com/watch?v=27yX3UVniWw",
  "Linear Alternating Pogos": "https://www.youtube.com/watch?v=KVlrbugvLcg",
  "Linear Pogo Jumps": "https://www.youtube.com/watch?v=tyasPPd-wzs",
  "Linear Pogos": "https://www.youtube.com/watch?v=PFkn7hh_eYE",
  "Low Back Pedal Walks": "https://www.youtube.com/watch?v=Iem2YUpo5T0",
  "Low Level Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Low Level Single Leg Box Jump": "https://www.youtube.com/watch?v=jxfGunNZaFw",
  "Low Squat Jumps to Vertical": "https://www.youtube.com/watch?v=6mshdP-Oi80",
  "Med Ball Backwards Toss": "https://www.youtube.com/watch?v=qPJWj_IVyXc",
  "Med Ball Reactive Chest Pass": "https://www.youtube.com/watch?v=cIbeRRTD4HU",
  "Med Ball Vertical Toss": "https://www.youtube.com/watch?v=ocLsH3czGMA",
  "Monster Walk": "https://www.youtube.com/watch?v=WjgMwyAqYFc",
  "Neutral Grip Pull Downs": "https://strengthcamp.com/movements/lat-pull-down/",
  "Non-CM Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Non-CM Vertical Toss": "https://www.youtube.com/watch?v=QLuQ7QfpScw",
  "Nordic Hamstring Curls": "https://www.youtube.com/watch?v=ccKOpE2KaXQ",
  "Nordic Hamstrings": "https://www.youtube.com/watch?v=T_oN089mQbc",
  "Oscillatory Bulgarian Split Squat": "https://www.youtube.com/watch?v=mVU8jNNmIqs",
  "Oscillatory Low Squat Jumps": "https://www.youtube.com/watch?v=x39EUpjgs9I",
  "Oscillatory Split Squat": "https://www.youtube.com/watch?v=AS7HIJ_q17A",
  "Overcoming Isometrics Bench Press": "https://www.youtube.com/watch?v=Qlgfj1OrDNo",
  "Overcoming Isometrics Trap Bar Split Squats": "https://www.youtube.com/watch?v=C40e0Ayj-To",
  "Overhead Press": "http://overtimeathletes.com/movements/strength/upper/push/vertical/overhead-press/",
  "Pallof Press": "https://www.youtube.com/watch?v=K_toen6eTHo",
  "Power Bounds": "http://overtimeathletes.com/movements/power/horizontal/bounds/",
  "Power Skips": "https://www.youtube.com/watch?v=DdkM2bYxz3w",
  "Prone Blackburns": "https://www.youtube.com/watch?v=tZ1Dz2bVn1M",
  "Prone Cobra": "https://www.youtube.com/watch?v=t1c-RF5Kg-o",
  "Prone Swimmers": "https://www.youtube.com/watch?v=dAOJUgoD-mg",
  "Pull Ups": "https://strengthcamp.com/movements/pull-ups/",
  "Reactive Band Bench Press": "https://www.youtube.com/watch?v=27yX3UVniWw",
  "Reactive Band Squat": "https://www.youtube.com/watch?v=w-Fe1iz5dyo",
  "Rebound Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Rebound Vertical Jumps": "https://www.youtube.com/watch?v=-UVvuYUdeq4",
  "Rolling DB Tricep Extension": "http://overtimeathletes.com/movements/strength/upper/arms-2/extension/dumbbell-skull-crushers/",
  "Rope or Towel Pull Ups": "https://strengthcamp.com/movements/pull-ups/",
  "Russian Lunges": "https://www.youtube.com/watch?v=WF8XL8oXyzU",
  "Russian Speed Lunges": "https://www.youtube.com/watch?v=lK7QDzC-sPo",
  "Seal Walks": "https://www.youtube.com/watch?v=8zmcQTNoe-Q",
  "Seated Box Jumps": "https://www.youtube.com/watch?v=TnxDW2cRLw8",
  "Seated MB Vertical Toss": "https://www.youtube.com/watch?v=4wyWfZX7jR8",
  "Seated Twist": "https://www.youtube.com/watch?v=RS8UxSqEZLA",
  "Side Plank Hip Lifts": "https://www.youtube.com/watch?v=qvh27jn39jw",
  "Single Arm Row": "https://www.youtube.com/watch?v=-zCoQYFLWCI",
  "Single Leg Box Jump": "https://www.youtube.com/watch?v=jxfGunNZaFw",
  "Single Leg Box Jumps": "https://www.youtube.com/watch?v=jxfGunNZaFw",
  "Single Leg Hip Thrust": "https://www.youtube.com/watch?v=qzddvnNVIOM",
  "Single Leg Linear Pogos": "https://www.youtube.com/watch?v=PFkn7hh_eYE",
  "Single Leg Snap Downs": "https://www.youtube.com/watch?v=2HbYWsV5biY",
  "Single Leg Stationary Pogo Jumps": "https://www.youtube.com/watch?v=WiA9B1iC6t0",
  "Single Leg Stationary Pogos": "https://www.youtube.com/watch?v=WiA9B1iC6t0",
  "Single Leg Trap Bar Deadlifts": "https://www.youtube.com/watch?v=bG8ABTw7M68",
  "Single Leg Tuck Jumps": "https://www.youtube.com/watch?v=6dRJtKYGnAY",
  "Snap Downs": "https://www.youtube.com/watch?v=2HbYWsV5biY",
  "Sprinter Step Up Launches": "https://www.youtube.com/watch?v=8nKz272nVs4",
  "Sprinter Step Up MB Toss": "https://www.youtube.com/watch?v=KViiBN6gVPY",
  "Squat Chops": "https://www.youtube.com/watch?v=oL2dB5P7gw8",
  "Squat Jumps": "https://www.youtube.com/watch?v=x39EUpjgs9I",
  "Staggered Stance Med Ball Vertical Toss": "https://www.youtube.com/watch?v=ocLsH3czGMA",
  "Standing Russian Twist": "https://www.youtube.com/watch?v=8VKpPuQmQyE",
  "Stationary Alternating Pogo Jumps": "https://www.youtube.com/watch?v=Knvvx4Jpzak",
  "Stationary Alternating Pogos": "https://www.youtube.com/watch?v=mW4vt3jcuAw",
  "Stationary Pogo Jumps": "https://www.youtube.com/watch?v=WiA9B1iC6t0",
  "Stationary Pogos": "https://www.youtube.com/watch?v=WiA9B1iC6t0",
  "Stationary Pulsing Pogos": "https://www.youtube.com/watch?v=KfxXiLyeHQc",
  "Suitcase Carry": "https://www.youtube.com/watch?v=Ikpffn2rucQ",
  "Suitcase Lunges": "https://www.youtube.com/watch?v=ZbmBZyrEEcA",
  "Swiss Ball Stir the Pot": "https://www.youtube.com/watch?v=1TEn_M9KFfU",
  "Trap Bar Deadlift": "https://www.youtube.com/watch?v=bG8ABTw7M68",
  "Trap Bar Deadlift (Low Handle)": "https://www.youtube.com/watch?v=bG8ABTw7M68",
  "Trap Bar Deadlift (off 2” blocks)": "https://www.youtube.com/watch?v=bG8ABTw7M68",
  "Tuck Jumps": "https://www.youtube.com/watch?v=6dRJtKYGnAY",
  "Underhand Med Ball Vertical Toss": "https://www.youtube.com/watch?v=NeaV7uYJpGg",
  "Vertical Jump": "https://www.youtube.com/watch?v=qmiaSj_eT48",
  "Wall Slides": "https://www.youtube.com/watch?v=YvmIld0QYKQ",
  "Weighted Hip Thrust": "https://www.youtube.com/watch?v=2m3eYQxQ5hI",
  "Weighted Hyperextensions": "https://www.youtube.com/watch?v=D_fgMVuDkgw",
  "Weighted SL Hip Thrust": "https://www.youtube.com/watch?v=qzddvnNVIOM"
};

// 嵌套 YouTube 视频的 ID 映射库
const EVA_EX_YOUTUBE_IDS = {
  "Ab Wheel": "j41bASIRzvo",
  "Alternating Lunge Jumps": "FgtEMhlm8lg",
  "Alternating Sprinter Step Ups": "Z_IiUhVs4HI",
  "Approach Box Jumps": "TnxDW2cRLw8",
  "Approach Single Leg Box Jump": "jxfGunNZaFw",
  "Approach Single Leg Vertical Jumps": "qmiaSj_eT48",
  "Approach Tuck Jump to Low Squat Landing": "qZh5XTdhrK8",
  "Approach Tuck Jump to Split Lunge Landing": "QJskYpKndgw",
  "BB Curls": "4tT6n_VEORA",
  "BB Iso Squat": "EwkBcH1ghZ8",
  "BB Iso Sumo Squat": "EwkBcH1ghZ8",
  "BB Oscillatory Low Squat": "zoUyB1k62FU",
  "BB Oscillatory Sumo Squat": "zoUyB1k62FU",
  "BB RDL": "CtjDKM5MkvE",
  "BB Rack Pulls": "4qtp361EZJg",
  "BB Reverse Lunge": "gJAflXsoa6A",
  "Back Squat": "w-Fe1iz5dyo",
  "Band Assisted Alternating Lunge Jumps": "FgtEMhlm8lg",
  "Band Assisted Jumps": "YAOWJdT__O4",
  "Band Assisted Single Leg Jumps": "MxUsfUZNqkM",
  "Band Assisted Single Leg Pogos": "Z7u6afb7JRE",
  "Band Assisted Squat Jumps": "6mshdP-Oi80",
  "Band Assisted Stationary Alternating Pogo Jumps": "Knvvx4Jpzak",
  "Band Assisted Stationary Pogos": "WiA9B1iC6t0",
  "Band Assisted Stationary Pulsing Pogos": "KfxXiLyeHQc",
  "Band Box Squat": "9LEnmKXl--U",
  "Band Facepull to External Rotation": "Uk_UlIhc6a4",
  "Band Facepulls": "naKAEmPUWdw",
  "Band Glute Bridge with Abduction": "6Brg1MgQcVA",
  "Band Pin Press": "QtEAgxEeAKw",
  "Band Snatch": "qMMjQxUjLeQ",
  "Band TKE’s": "bU-Yb4KdpNw",
  "Band Tricep Extensions": "VHFufUUSHig",
  "Banded Kettlebell Swing": "fsyg_pZfarA",
  "Bench Press": "wvEfyPtT44U",
  "Box Jump": "jxfGunNZaFw",
  "Box Jumps": "TnxDW2cRLw8",
  "Bulgarian Split Squat": "",
  "Bulgarian Split Squat (Heel Raised)": "RrP9PHcjj0g",
  "Bulgarian Split Squat (heel elevated)": "RrP9PHcjj0g",
  "Bulgarian Split Squat Jumps": "6mshdP-Oi80",
  "Bulgarian Split Squat to Foam": "RrP9PHcjj0g",
  "Cable Tricep Extension": "UZpPZ1O8uYo",
  "Cable Woodchops": "j1cf5K0v_0k",
  "DB Alternating Lunge Jumps": "FgtEMhlm8lg",
  "DB Hammer Curls": "s1ZHxg7wiFA",
  "DB Iso Bulgarian Split Squat": "RrP9PHcjj0g",
  "DB Iso Split Squat": "GEuBgO1xRzc",
  "DB Linear Pogos": "tyasPPd-wzs",
  "DB Oscillatory Bulgarian Split Squat": "mVU8jNNmIqs",
  "DB Oscillatory Split Squat": "AS7HIJ_q17A",
  "DB RDL": "xEvkelNr_-A",
  "DB Reverse Lunge": "gJAflXsoa6A",
  "DB Reverse Lunge (heel elevated)": "gJAflXsoa6A",
  "DB Squat Jumps": "6mshdP-Oi80",
  "DB Stationary Alternating Pogo Jumps": "mW4vt3jcuAw",
  "DB Stationary Pogos": "WiA9B1iC6t0",
  "DB Z Press": "",
  "Decel Sprinter Step Ups": "VWUv_YoxGEw",
  "Decel Step Ups": "WjkXTrwjMnE",
  "Depth Drops": "7HdHLuAzBes",
  "Dump the Buckets": "SCQ9DQeoE_c",
  "EZ Bar Curls": "4tT6n_VEORA",
  "EZ Bar Skull Crushers": "ZC-yUUQDJnA",
  "Eccentric Band Back Squat": "eUEAAEOotnQ",
  "Eccentric Band Bench Press": "27yX3UVniWw",
  "Eccentric Box Jumps": "TnxDW2cRLw8",
  "Eccentric Single Leg Box Jumps": "jxfGunNZaFw",
  "Elevated DB Reverse Lunge": "gJAflXsoa6A",
  "Explosive Band Push Ups": "5UZ5KEjUPOU",
  "Floor Press": "WQK3Byyt1zk",
  "Goblet Lateral Lunge": "DW6vMEt8vCI",
  "Half Kneeling Box Jumps": "TnxDW2cRLw8",
  "Half Kneeling Landmine Press": "b-5t7HOABqc",
  "Half Kneeling Vertical Toss": "XjlSjGfc9cg",
  "Hanging Leg Raise": "4Ch5YMjbTKA",
  "Hyperextensions": "D_fgMVuDkgw",
  "Incline Alternating Row": "Wqtg3bztCpY",
  "Incline DB Hammer Curls": "s1ZHxg7wiFA",
  "Incline Plate Press": "ZcciCMEC3mI",
  "Incline Rear Delt Raise": "06NT9wsO95A",
  "Incline Rear Delt Raise with External Rotation": "06NT9wsO95A",
  "Incline Row": "Wqtg3bztCpY",
  "Iso Band Back Squat": "w-Fe1iz5dyo",
  "Iso Band Bench Press": "wvEfyPtT44U",
  "Iso Step Downs": "",
  "Iso-Extreme Bulgarian Split Squat": "",
  "Iso-Extreme Nordic Hamstrings": "T_oN089mQbc",
  "Iso-Extreme SL Hip Thrust": "kXUMRXNgs7o",
  "Iso-Extreme Split Squat": "NIVtkEKNhaE",
  "Iso-Extreme Squat": "T67pP7Jm6mw",
  "Iso-Extreme Sumo Squat": "B84ZeeYb4yM",
  "Kettlebell Swing": "fsyg_pZfarA",
  "Landmine Press": "b-5t7HOABqc",
  "Larsen Bench Press": "27yX3UVniWw",
  "Linear Alternating Pogos": "KVlrbugvLcg",
  "Linear Pogo Jumps": "tyasPPd-wzs",
  "Linear Pogos": "PFkn7hh_eYE",
  "Low Back Pedal Walks": "Iem2YUpo5T0",
  "Low Level Box Jumps": "TnxDW2cRLw8",
  "Low Level Single Leg Box Jump": "jxfGunNZaFw",
  "Low Squat Jumps to Vertical": "6mshdP-Oi80",
  "Med Ball Backwards Toss": "qPJWj_IVyXc",
  "Med Ball Reactive Chest Pass": "cIbeRRTD4HU",
  "Med Ball Vertical Toss": "ocLsH3czGMA",
  "Monster Walk": "WjgMwyAqYFc",
  "Neutral Grip Pull Downs": "",
  "Non-CM Box Jumps": "TnxDW2cRLw8",
  "Non-CM Vertical Toss": "QLuQ7QfpScw",
  "Nordic Hamstring Curls": "ccKOpE2KaXQ",
  "Nordic Hamstrings": "T_oN089mQbc",
  "Oscillatory Bulgarian Split Squat": "mVU8jNNmIqs",
  "Oscillatory Low Squat Jumps": "x39EUpjgs9I",
  "Oscillatory Split Squat": "AS7HIJ_q17A",
  "Overcoming Isometrics Bench Press": "Qlgfj1OrDNo",
  "Overcoming Isometrics Trap Bar Split Squats": "C40e0Ayj-To",
  "Overhead Press": "",
  "Pallof Press": "K_toen6eTHo",
  "Power Bounds": "",
  "Power Skips": "DdkM2bYxz3w",
  "Prone Blackburns": "tZ1Dz2bVn1M",
  "Prone Cobra": "t1c-RF5Kg-o",
  "Prone Swimmers": "dAOJUgoD-mg",
  "Pull Ups": "",
  "Reactive Band Bench Press": "27yX3UVniWw",
  "Reactive Band Squat": "w-Fe1iz5dyo",
  "Rebound Box Jumps": "TnxDW2cRLw8",
  "Rebound Vertical Jumps": "-UVvuYUdeq4",
  "Rolling DB Tricep Extension": "",
  "Rope or Towel Pull Ups": "",
  "Russian Lunges": "WF8XL8oXyzU",
  "Russian Speed Lunges": "lK7QDzC-sPo",
  "Seal Walks": "8zmcQTNoe-Q",
  "Seated Box Jumps": "TnxDW2cRLw8",
  "Seated MB Vertical Toss": "4wyWfZX7jR8",
  "Seated Twist": "RS8UxSqEZLA",
  "Side Plank Hip Lifts": "qvh27jn39jw",
  "Single Arm Row": "-zCoQYFLWCI",
  "Single Leg Box Jump": "jxfGunNZaFw",
  "Single Leg Box Jumps": "jxfGunNZaFw",
  "Single Leg Hip Thrust": "qzddvnNVIOM",
  "Single Leg Linear Pogos": "PFkn7hh_eYE",
  "Single Leg Snap Downs": "2HbYWsV5biY",
  "Single Leg Stationary Pogo Jumps": "WiA9B1iC6t0",
  "Single Leg Stationary Pogos": "WiA9B1iC6t0",
  "Single Leg Trap Bar Deadlifts": "bG8ABTw7M68",
  "Single Leg Tuck Jumps": "6dRJtKYGnAY",
  "Snap Downs": "2HbYWsV5biY",
  "Sprinter Step Up Launches": "8nKz272nVs4",
  "Sprinter Step Up MB Toss": "KViiBN6gVPY",
  "Squat Chops": "oL2dB5P7gw8",
  "Squat Jumps": "x39EUpjgs9I",
  "Staggered Stance Med Ball Vertical Toss": "ocLsH3czGMA",
  "Standing Russian Twist": "8VKpPuQmQyE",
  "Stationary Alternating Pogo Jumps": "Knvvx4Jpzak",
  "Stationary Alternating Pogos": "mW4vt3jcuAw",
  "Stationary Pogo Jumps": "WiA9B1iC6t0",
  "Stationary Pogos": "WiA9B1iC6t0",
  "Stationary Pulsing Pogos": "KfxXiLyeHQc",
  "Suitcase Carry": "Ikpffn2rucQ",
  "Suitcase Lunges": "ZbmBZyrEEcA",
  "Swiss Ball Stir the Pot": "1TEn_M9KFfU",
  "Trap Bar Deadlift": "bG8ABTw7M68",
  "Trap Bar Deadlift (Low Handle)": "bG8ABTw7M68",
  "Trap Bar Deadlift (off 2” blocks)": "bG8ABTw7M68",
  "Tuck Jumps": "6dRJtKYGnAY",
  "Underhand Med Ball Vertical Toss": "NeaV7uYJpGg",
  "Vertical Jump": "qmiaSj_eT48",
  "Wall Slides": "YvmIld0QYKQ",
  "Weighted Hip Thrust": "2m3eYQxQ5hI",
  "Weighted Hyperextensions": "D_fgMVuDkgw",
  "Weighted SL Hip Thrust": "qzddvnNVIOM"
};

// 核心讲解句型模板
const COACHING_TEMPLATES = {
    "iso-extreme": "🏋️‍♂️ **超极限等长收缩 (Iso-Extreme)**：在最深关节受力角度下进行长达 90-180 秒的静止收缩。要领：千万不要‘被动承受重量’，必须意念中拼命发力将自己往地里‘深拉’，主动激活并锁死肌肉。这能迅速重塑跟腱与关节囊刚性，募集最高阈值的快缩肌纤维，从根本上隔离伤病、纠正膝盖代偿并杜绝髌骨肌腱炎。",
    "oscillatory": "🌀 **震荡性等长收缩 (Oscillatory)**：在最深关节受力位，进行超小幅度（约1-2英寸）极快速度的主动起伏震荡。要领：动作要像高频钢簧一样快速交替收紧和放松，不要进行慢速大范围运动。这能极大化兴奋中枢神经系统（CNS），训练快缩肌纤维的瞬时弹性缩放，提高牵拉反射率与弹性释放速度。",
    "pogo": "🦘 **跟腱超等长刚性弹跳 (Pogo Jumps)**：锁死双膝与双髋，全身直立。要领：落地触地时间尽可能缩短，脚后跟尽量不触地，纯靠足踝复合体与小腿跟腱的被动拉伸弹性‘反射起飞’。这是 Barnard 教练升级赛车避震系统（足踝刚度）的核心动作，防起跳漏力，是顶级弹跳的刚性基础。",
    "depth drop": "🛑 **高冲击降落减速落地 (Depth Drops / Altitude Drops)**：从高处箱子上自然跨步走下（禁止向上起跳），在双脚触地瞬间全身关节和核心肌肉群百分之百瞬间紧绷，无声落地。要领：落地后像雕像一样在极短时间内死锁，不准有二次多余的晃动。落地越安静，说明肌肉的动能吸收与减速离心效率越高。这是阶段二离心吸能（升级刹车系统）的最硬核动作。",
    "snap down": "📉 **极速下落控制 (Snap Down)**：直立站姿或垫脚高举，然后突然极速收缩髋关节将身体向下“砸”入深蹲或单脚分腿蹲姿态。要领：利用重力与主动收缩在零点几秒内完成极速下落刹车，落地锁死。这是离心减速与落地缓冲训练的初级王牌动作。",
    "nordic": "🍗 **北欧腘绳肌反向弯举 (Nordic Hamstring Curls)**：双膝跪地固定脚踝，躯干保持一条直线。要领：在离心下降阶段极其控制身体前倾速度，用腘绳肌顶住重力超慢速下降，直至脸部接近地面，再以双手推起。这是重塑腘绳肌离心吸能与伸髋能量的黄金动作，能极大强化助跑弹跳转换率并隔离后链伤病。",
    "trap bar": "🏋️‍♀️ **六角死锁拉 (Trap Bar Deadlift)**：立足六角框中央，屈髋下蹲，收紧核心，保持背部平直。向心起站时，双脚像推开地球一样发力，在顶部用力夹紧臀大肌。这是评估垂直弹跳绝对发动机力量的基准动作（目标达到自重2.2x-2.6x），能显著增加伸髋爆发力与功率输出。",
    "box squat": "📦 **静止箱式深蹲 (Box Squat)**：下落坐箱，彻底停顿 1 秒卸掉所有离心弹性动能。要领：完全静止后，排除一切牵拉反射惯性，中枢神经瞬间向心爆发站起。这是阶段三（Propulsion）最核心动作，主攻纯肌肉收缩发力率（RFD）。",
    "pin press": "📌 **销钉支撑推 (Pin Press)**：将杠铃静置在安全销（Pins）上，消除下落的离心预拉伸。要领：在彻底静止状态下最大力量爆发式推起杠铃，主攻纯向心收缩发力率与神经募招。",
    "bench press": "💪 **阻力带卧推 (Bench Press)**：保持肩胛骨内收下沉，胸椎起拱，双脚踩实地面。根据当周节奏：如果是 `[1|5|X]`，在胸前死锁静止5秒（最大神经动员），再以爆裂速度“X”推起；如果是 `[6|X|X]`，则超慢控制离心6秒下落，消除一切松懈瞬间向心爆发。",
    "squat": "🦵 **阻力带背蹲/深蹲 (Back Squat / Front Squat)**：下落时膝盖向脚尖方向外开，臀部向后下沉。根据节奏：如果是 `[1|5|X]`，在四分之一蹲位（约45度角，模拟专项奔跑角度）等长死锁停顿5秒，强力激活快缩肌；如果是 `[6|X|X]`，离心超慢下落6秒蓄能。向心阶段爆发炸裂站起。",
    "lunge": "🚶 **单腿分腿蹲/箭步蹲 (Split Squat / Lunge)**：前脚受力脚，后脚起平衡作用。根据 tempo 或等长要求执行。重点解决左右下肢肌力不对称，强化单侧膝关节稳定与股四头肌内侧头（VMO）刚硬度。"
};

// 动态合成每个动作的中文讲解与指导说明
function getExerciseCoachingDetails(exName) {
    const nameLower = exName.toLowerCase();
    
    // Find matching template
    let matchedTip = "🏋️‍♂️ **常规训练动作**：请严格按照当周 prescribed tempo（节奏）和组次数执行。在向心阶段（起发力阶段）确保用意念以最大速度加速推起杠铃，激活中枢神经；在负重或自重落地时保持关节绝对稳定，脊柱呈中性，防止晃动。";
    
    for (let key in COACHING_TEMPLATES) {
        if (nameLower.includes(key)) {
            matchedTip = COACHING_TEMPLATES[key];
            break;
        }
    }
    
    // Custom fine-tuned overrides for specific movements
    if (nameLower.includes("wall slide")) {
        matchedTip = "💆 **肩胛壁滑 (Wall Slides)**：靠墙贴实，腰椎扁平不要起拱，双手臂呈 W 状紧贴墙壁慢慢向上滑动至 Y 状。这是顶级的肩胛稳定性矫正动作，防止上肢在卧推/硬拉受力时滑脱代偿。";
    } else if (nameLower.includes("groiner")) {
        matchedTip = "🦎 **深蹲侧步开胯 (Groiners)**：双手撑地呈平板支撑，单脚向前跨至同侧手外侧，尽量下沉髋部拉伸腹股沟，结合胸椎旋转更佳。这能极大释放髋屈肌粘连，为深蹲和起跳释放髋关节活动度。";
    } else if (nameLower.includes("nordic ham")) {
        matchedTip = "🍗 **等长北欧腘绳肌 (Nordic Hamstrings)**：膝盖下方垫软垫，小腿固定。离心下落前前倾至受力极限，静止保持 5 秒后撑回，或进行最大心力控制前倾速度。极速强化腘绳肌，防御腘绳肌拉伤与ACL撕裂。";
    } else if (nameLower.includes("towel pull up") || nameLower.includes("pull up")) {
        matchedTip = "🧗 **引体向上 (Pull Ups)**：双手抓握（毛巾抓握更佳以强化前臂握力），核心收紧。向上拉起时胸口贴杠，肩胛骨向后下内收。强化上身背部肌群，增加起跳摆臂的上拉动能转化。";
    } else if (nameLower.includes("pogo")) {
        matchedTip = "🦘 **跟腱超等长刚性弹跳 (Pogo Jumps)**：锁死双膝与双髋，全身直立。要领：落地触地时间尽可能缩短，脚后跟尽量不触地，纯靠足踝复合体与小腿跟腱的被动拉伸弹性‘反射起飞’。这是跟腱与踝关节刚性强化的王牌动作，防起跳漏力。";
    }
    
    const uri = EVA_EX_LINKS[exName] || "";
    const ytId = EVA_EX_YOUTUBE_IDS[exName] || "";
    
    return {
        name: exName,
        tip: matchedTip,
        videoUrl: uri,
        youtubeId: ytId
    };
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EVA_EX_LINKS, EVA_EX_YOUTUBE_IDS, getExerciseCoachingDetails };
}
